name: nugget-notebooks
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.2
  - requests==2.21.0
  - xarray==0.13.0
  - pandas==0.23.4
  - numpy==1.15.4
  - matplotlib==3.0.3
  - jupyter==1.0.0
  - netCDF4==1.4.0
  - cartopy==0.17.0
  - geopy==1.17.0
  - dask==2.17.2
  - echopype==0.3.2
  - beautifulsoup4==4.9.1
